# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "custom-simple"
license = "MIT"
licenselink = ""
description = ""
homepage = ""
tags = ["custom", "theme"]
features = ["", ""]
min_version = 0.18

[author]
  name = "Savith K J"
  homepage = "savitha.github.io"
